use rand::prelude::*;
use rand_float::ImprovedFloat;

fn main() {
    let rng = StdRng::from_entropy();

    println!(
        "10 random, tiny floats, generated by \
        a proposed updated implementation"
    );

    rng.sample_iter(ImprovedFloat)
        .filter(|&value| value < 0.0000001)
        .take(10)
        .for_each(|value: f64| println!("{value}: 0x{bits:X}", bits = value.to_bits()))
}
